In [2]:
!pip install yfinance
!pip install numpy
!pip install sklearn


In [3]:
import yfinance

STOCK_SYMBOL = "^GSPC"
START_DATE = "2013-01-01"
END_DATE = "2023-07-09"

dataframe = yfinance.download(tickers = STOCK_SYMBOL,
                              start = START_DATE,
                              end = END_DATE)

dataframe

[*********************100%***********************]  1 of 1 completed


Open         High          Low        Close    Adj Close  \
Date                                                                          
2013-01-02  1426.189941  1462.430054  1426.189941  1462.420044  1462.420044   
2013-01-03  1462.420044  1465.469971  1455.530029  1459.369995  1459.369995   
2013-01-04  1459.369995  1467.939941  1458.989990  1466.469971  1466.469971   
2013-01-07  1466.469971  1466.469971  1456.619995  1461.890015  1461.890015   
2013-01-08  1461.890015  1461.890015  1451.640015  1457.150024  1457.150024   
...                 ...          ...          ...          ...          ...   
2023-06-30  4422.439941  4458.479980  4422.439941  4450.379883  4450.379883   
2023-07-03  4450.479980  4456.459961  4442.290039  4455.589844  4455.589844   
2023-07-05  4442.040039  4454.060059  4436.609863  4446.819824  4446.819824   
2023-07-06  4422.620117  4422.620117  4385.049805  4411.589844  4411.589844   
2023-07-07  4404.540039  4440.390137  4397.399902  4398.950195  4398.950195   

                Volume  
Date                    
2013-01-02  4202600000  
2013-01-03  3829730000  
2013-01-04  3424290000  
2013-01-07  3304970000  
2013-01-08  3601600000  
...                ...  
2023-06-30  3923450000  
2023-07-03  2034280000  
2023-07-05  3482620000  
2023-07-06  3682020000  
2023-07-07  3630480000  

[2646 rows x 6 columns]

In [4]:
import numpy

DECREASED = 1

INCREASED = 0

dataframe["Volume Increase/Decrease"] = numpy.where(dataframe["Volume"].shift(-1) > dataframe["Volume"],
                                                    DECREASED,
                                                    INCREASED)

dataframe

Open         High          Low        Close    Adj Close  \
Date                                                                          
2013-01-02  1426.189941  1462.430054  1426.189941  1462.420044  1462.420044   
2013-01-03  1462.420044  1465.469971  1455.530029  1459.369995  1459.369995   
2013-01-04  1459.369995  1467.939941  1458.989990  1466.469971  1466.469971   
2013-01-07  1466.469971  1466.469971  1456.619995  1461.890015  1461.890015   
2013-01-08  1461.890015  1461.890015  1451.640015  1457.150024  1457.150024   
...                 ...          ...          ...          ...          ...   
2023-06-30  4422.439941  4458.479980  4422.439941  4450.379883  4450.379883   
2023-07-03  4450.479980  4456.459961  4442.290039  4455.589844  4455.589844   
2023-07-05  4442.040039  4454.060059  4436.609863  4446.819824  4446.819824   
2023-07-06  4422.620117  4422.620117  4385.049805  4411.589844  4411.589844   
2023-07-07  4404.540039  4440.390137  4397.399902  4398.950195  4398.950195   

                Volume  Volume Increase/Decrease  
Date                                              
2013-01-02  4202600000                         0  
2013-01-03  3829730000                         0  
2013-01-04  3424290000                         0  
2013-01-07  3304970000                         1  
2013-01-08  3601600000                         1  
...                ...                       ...  
2023-06-30  3923450000                         0  
2023-07-03  2034280000                         1  
2023-07-05  3482620000                         1  
2023-07-06  3682020000                         0  
2023-07-07  3630480000                         0  

[2646 rows x 7 columns]

In [5]:
dataframe["Returns"] = dataframe["Adj Close"].pct_change()
dataframe = dataframe.dropna()

dataframe

Open         High          Low        Close    Adj Close  \
Date                                                                          
2013-01-03  1462.420044  1465.469971  1455.530029  1459.369995  1459.369995   
2013-01-04  1459.369995  1467.939941  1458.989990  1466.469971  1466.469971   
2013-01-07  1466.469971  1466.469971  1456.619995  1461.890015  1461.890015   
2013-01-08  1461.890015  1461.890015  1451.640015  1457.150024  1457.150024   
2013-01-09  1457.150024  1464.729980  1457.150024  1461.020020  1461.020020   
...                 ...          ...          ...          ...          ...   
2023-06-30  4422.439941  4458.479980  4422.439941  4450.379883  4450.379883   
2023-07-03  4450.479980  4456.459961  4442.290039  4455.589844  4455.589844   
2023-07-05  4442.040039  4454.060059  4436.609863  4446.819824  4446.819824   
2023-07-06  4422.620117  4422.620117  4385.049805  4411.589844  4411.589844   
2023-07-07  4404.540039  4440.390137  4397.399902  4398.950195  4398.950195   

                Volume  Volume Increase/Decrease   Returns  
Date                                                        
2013-01-03  3829730000                         0 -0.002086  
2013-01-04  3424290000                         0  0.004865  
2013-01-07  3304970000                         1 -0.003123  
2013-01-08  3601600000                         1 -0.003242  
2013-01-09  3674390000                         1  0.002656  
...                ...                       ...       ...  
2023-06-30  3923450000                         0  0.012269  
2023-07-03  2034280000                         1  0.001171  
2023-07-05  3482620000                         1 -0.001968  
2023-07-06  3682020000                         0 -0.007923  
2023-07-07  3630480000                         0 -0.002865  

[2645 rows x 8 columns]

In [6]:
BUY  = 1

SELL = 0

dataframe["Buy/Sell"] = numpy.where(dataframe["Adj Close"].shift(-1) > dataframe["Adj Close"],
                                    BUY,
                                    SELL)

dataframe["High vs Low"] = (dataframe["High"] - dataframe["Low"])/dataframe["Low"]

dataframe

C:\Users\pc2\AppData\Local\Temp\ipykernel_24872\2731393750.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Buy/Sell"] = numpy.where(dataframe["Adj Close"].shift(-1) > dataframe["Adj Close"],
C:\Users\pc2\AppData\Local\Temp\ipykernel_24872\2731393750.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["High vs Low"] = (dataframe["High"] - dataframe["Low"])/dataframe["Low"]


Open         High          Low        Close    Adj Close  \
Date                                                                          
2013-01-03  1462.420044  1465.469971  1455.530029  1459.369995  1459.369995   
2013-01-04  1459.369995  1467.939941  1458.989990  1466.469971  1466.469971   
2013-01-07  1466.469971  1466.469971  1456.619995  1461.890015  1461.890015   
2013-01-08  1461.890015  1461.890015  1451.640015  1457.150024  1457.150024   
2013-01-09  1457.150024  1464.729980  1457.150024  1461.020020  1461.020020   
...                 ...          ...          ...          ...          ...   
2023-06-30  4422.439941  4458.479980  4422.439941  4450.379883  4450.379883   
2023-07-03  4450.479980  4456.459961  4442.290039  4455.589844  4455.589844   
2023-07-05  4442.040039  4454.060059  4436.609863  4446.819824  4446.819824   
2023-07-06  4422.620117  4422.620117  4385.049805  4411.589844  4411.589844   
2023-07-07  4404.540039  4440.390137  4397.399902  4398.950195  4398.950195   

                Volume  Volume Increase/Decrease   Returns  Buy/Sell  \
Date                                                                   
2013-01-03  3829730000                         0 -0.002086         1   
2013-01-04  3424290000                         0  0.004865         0   
2013-01-07  3304970000                         1 -0.003123         0   
2013-01-08  3601600000                         1 -0.003242         1   
2013-01-09  3674390000                         1  0.002656         1   
...                ...                       ...       ...       ...   
2023-06-30  3923450000                         0  0.012269         1   
2023-07-03  2034280000                         1  0.001171         0   
2023-07-05  3482620000                         1 -0.001968         0   
2023-07-06  3682020000                         0 -0.007923         0   
2023-07-07  3630480000                         0 -0.002865         0   

            High vs Low  
Date                     
2013-01-03     0.006829  
2013-01-04     0.006134  
2013-01-07     0.006762  
2013-01-08     0.007061  
2013-01-09     0.005202  
...                 ...  
2023-06-30     0.008149  
2023-07-03     0.003190  
2023-07-05     0.003933  
2023-07-06     0.008568  
2023-07-07     0.009776  

[2645 rows x 10 columns]

In [7]:
dataframe["Open vs Close"] = (dataframe["Open"] - dataframe["Close"]) / dataframe["Open"]

dataframe

C:\Users\pc2\AppData\Local\Temp\ipykernel_24872\3773814830.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Open vs Close"] = (dataframe["Open"] - dataframe["Close"]) / dataframe["Open"]


Open         High          Low        Close    Adj Close  \
Date                                                                          
2013-01-03  1462.420044  1465.469971  1455.530029  1459.369995  1459.369995   
2013-01-04  1459.369995  1467.939941  1458.989990  1466.469971  1466.469971   
2013-01-07  1466.469971  1466.469971  1456.619995  1461.890015  1461.890015   
2013-01-08  1461.890015  1461.890015  1451.640015  1457.150024  1457.150024   
2013-01-09  1457.150024  1464.729980  1457.150024  1461.020020  1461.020020   
...                 ...          ...          ...          ...          ...   
2023-06-30  4422.439941  4458.479980  4422.439941  4450.379883  4450.379883   
2023-07-03  4450.479980  4456.459961  4442.290039  4455.589844  4455.589844   
2023-07-05  4442.040039  4454.060059  4436.609863  4446.819824  4446.819824   
2023-07-06  4422.620117  4422.620117  4385.049805  4411.589844  4411.589844   
2023-07-07  4404.540039  4440.390137  4397.399902  4398.950195  4398.950195   

                Volume  Volume Increase/Decrease   Returns  Buy/Sell  \
Date                                                                   
2013-01-03  3829730000                         0 -0.002086         1   
2013-01-04  3424290000                         0  0.004865         0   
2013-01-07  3304970000                         1 -0.003123         0   
2013-01-08  3601600000                         1 -0.003242         1   
2013-01-09  3674390000                         1  0.002656         1   
...                ...                       ...       ...       ...   
2023-06-30  3923450000                         0  0.012269         1   
2023-07-03  2034280000                         1  0.001171         0   
2023-07-05  3482620000                         1 -0.001968         0   
2023-07-06  3682020000                         0 -0.007923         0   
2023-07-07  3630480000                         0 -0.002865         0   

            High vs Low  Open vs Close  
Date                                    
2013-01-03     0.006829       0.002086  
2013-01-04     0.006134      -0.004865  
2013-01-07     0.006762       0.003123  
2013-01-08     0.007061       0.003242  
2013-01-09     0.005202      -0.002656  
...                 ...            ...  
2023-06-30     0.008149      -0.006318  
2023-07-03     0.003190      -0.001148  
2023-07-05     0.003933      -0.001076  
2023-07-06     0.008568       0.002494  
2023-07-07     0.009776       0.001269  

[2645 rows x 11 columns]

In [8]:
X = numpy.array(dataframe.drop(["Buy/Sell", "Close"], axis = 1))

y = numpy.array(dataframe["Buy/Sell"])

X

array([[ 1.46242004e+03,  1.46546997e+03,  1.45553003e+03, ...,
        -2.08561749e-03,  6.82908714e-03,  2.08561749e-03],
       [ 1.45937000e+03,  1.46793994e+03,  1.45898999e+03, ...,
         4.86509632e-03,  6.13434721e-03, -4.86509632e-03],
       [ 1.46646997e+03,  1.46646997e+03,  1.45662000e+03, ...,
        -3.12311615e-03,  6.76221363e-03,  3.12311615e-03],
       ...,
       [ 4.44204004e+03,  4.45406006e+03,  4.43660986e+03, ...,
        -1.96831841e-03,  3.93322736e-03, -1.07603378e-03],
       [ 4.42262012e+03,  4.42262012e+03,  4.38504980e+03, ...,
        -7.92251134e-03,  8.56781888e-03,  2.49405853e-03],
       [ 4.40454004e+03,  4.44039014e+03,  4.39739990e+03, ...,
        -2.86510054e-03,  9.77628493e-03,  1.26910953e-03]])

In [9]:
y

array([1, 0, 0, ..., 0, 0, 0])

In [10]:
from sklearn.neural_network import BernoulliRBM

NUMBER_OF_COMPONENTS = 2

neural_network = BernoulliRBM(n_components = NUMBER_OF_COMPONENTS)

neural_network.fit(X)

BernoulliRBM(n_components=2)

In [11]:
neural_network.score_samples(X)

array([-0.00000000e+00, -4.71859200e+06, -0.00000000e+00, ...,
       -0.00000000e+00, -0.00000000e+00, -6.23832463e+00])

In [12]:
neural_network.transform(X)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
from sklearn.linear_model import LogisticRegression

logistic_regression = LogisticRegression()

NUMBER_OF_COMPONENTS = 2

neural_network_2 = BernoulliRBM(n_components = NUMBER_OF_COMPONENTS)

from sklearn.pipeline import Pipeline

classifier = Pipeline(steps = [("neural_network", neural_network_2),
                               ("logistic_regression", logistic_regression)])

In [20]:
X_train

array([[ 2.85580005e+03,  2.89214990e+03,  2.85580005e+03, ...,
         8.89528712e-03,  1.27284309e-02, -7.18538384e-03],
       [ 2.69094995e+03,  2.72766992e+03,  2.68133008e+03, ...,
        -5.00158842e-03,  1.72824093e-02,  3.45232696e-03],
       [ 2.11929004e+03,  2.12591992e+03,  2.10704004e+03, ...,
        -4.14131425e-03,  8.96038161e-03,  4.89320338e-03],
       ...,
       [ 2.44237988e+03,  2.44272998e+03,  2.40569995e+03, ...,
        -8.60002325e-03,  1.53926217e-02,  9.28599674e-03],
       [ 2.71580005e+03,  2.74776001e+03,  2.71373999e+03, ...,
         1.60283764e-02,  1.25362119e-02, -1.15987920e-02],
       [ 2.10407007e+03,  2.10407007e+03,  2.08536011e+03, ...,
        -2.91181466e-03,  8.97205277e-03,  2.34791874e-03]])

In [21]:
classifier.fit(X_train, y_train)

predictions = classifier.predict(X_test)

predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [22]:
from sklearn.metrics.classification import accuracy_score

accuracy_score(y_test, predictions)

ModuleNotFoundError: No module named 'sklearn.metrics.classification'